language: node_js
node_js: 8.9
services:
- mongodb
cache: npm
deploy:
  provider: heroku
  api_key:
    secure: U1zmTJT/YCCK1Yr1xc1gIHpW+X68CYbmhuxMEZnLVSadOzgJh0mB3ryGSPbyOVYIX67LyV+W2QeIsznvmTeb5Gy7wg3mGurI3B5hwgCMrC6ibSCTEmIROXO6jmW0DPnNCMYO1+nWcbpgevO2VR6SSOoWDie/WJIghPw5+qBMqH7n44gF4KXZCVtTQuWMhCH4vnlTxpoNHl3apUELxcArOkIgq3YjVxGwDVQQ6k0GVk6KEFI44sOqiKpBlULMuC188awtPZC4efuIFPmQ1sAmq89327LUZDBuBaerRkcwhUSiNaSL0Dhpc+Tk8PtPnR7Sk5vqhvpubyi/3QB7PxKKVSExNt74jP+TJgzNObTdek7T+lSlT92K9iLCN0VJpSDnZYK/8thuF8UCnrvSjxaiQbZHj1CFdir8kq8VMaRZR08XQ87x61w1NkwmrBhjwo0rhVMlSQaijgumQBsYQjSkBBq9XK1iXqe8Ls22Wwf001HJ2sEhxDaSpywi9w6otLDwyKQGf+sJ+zecBj1ZYAmSVXxeXDAsKp7dpaF4y6T00Y6dYP6itXAGczU+GSvzH7+amrlpd013uRwsVxyQy5aClyNxYV83Arfj4mYeEDqufm7FHQjOyrUrA5CJLHUwedLUzl+VQZsY5FZi87THydkqMbzzQSPifxQGJegCcO5FFa4=
  app: polifluence
  on:
    repo: mattgif/polifluence-api
